### ISSUE TITLE
body is not defined

### ISSUE THREAD

**Issue by 517pacifikal** [chen-yingfa/hexo-theme-fengye#1]
很喜欢您的主题，但我在应用时出现了问题
我在hexo-theme-fengye/index.ejs中有如下代码：

        <div class="flex flex-row items-center gap-1 group">
          <iconify-icon class="transition-transform
                group-hover:scale-125" width="24" icon="ic:baseline-computer"></iconify-icon>
          <a href="/coder" class="group-hover:underline">
            程序员
          </a>
        </div>

在项目根目录下的/source/coder/index.md中有如下内容：
`---
title: "我的博客文章"
date: 2023-11-18
layout: layout
---

# 我的第一篇博客文章

欢迎来到我的博客！这是我的第一篇文章。

## 一级标题

这是一级标题的内容。

### 二级标题

这是二级标题的内容。下面是一些列表：

- 列表项1
- 列表项2
- 列表项3`
然后在项目根目录下运行hexo g，终端得到结果：
`D:\Blog>hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 139 ms
INFO  Deleted: coder/coderIndex.html
ERROR
ReferenceError: D:\Blog\themes\hexo-theme-fengye\layout\layout.ejs:14
    12|   <%- partial('_partial/header', {cache: true}) %>
    13|   <main>
 >> 14|     <%- body %>
    15|   </main>
    16|   <%- partial('_partial/footer', {cache: true}) %>
    17|   <div class="

body is not defined
    at eval ("D:\\Blog\\themes\\hexo-theme-fengye\\layout\\layout.ejs":21:17)
    at layout (D:\Blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (D:\Blog\node_modules\hexo\dist\theme\view.js:125:67)
    at _View.render (D:\Blog\node_modules\hexo\dist\theme\view.js:50:21)
    at D:\Blog\node_modules\hexo\dist\hexo\index.js:58:29
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Blog\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:547:12)
    at resume_ (node:internal/streams/readable:1048:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
INFO  0 files generated in 35 ms`
如何解决呢？

**Comment by chen-yingfa** [comment]
请问你已经解决了吗？我这边好像无法复习

**Comment by 517pacifikal** [comment]
Thanks for your reply! I have solved this problem by developing the project again. I still don't know what was wrong with it, but the problem has been bypassed.&nbsp;


517&nbsp;pacifikal
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2023年11月23日(星期四) 晚上6:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [chen-yingfa/hexo-theme-fengye] body is not defined (Issue #1)





 
请问你已经解决了吗？我这边好像无法复习
